"""add promotion approvals

Revision ID: 347ef463db86
Revises: c8fc232e2891
Create Date: 2026-09-02 04:35:17.350893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '347ef463db86'
down_revision: Union[str, Sequence[str], None] = 'c8fc232e2891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotion_approvals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('genome_hash', sa.String(length=32), nullable=False),
    sa.Column('experiment_id', sa.String(length=100), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['genome_hash'], ['system_genomes.hash'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotion_approvals_genome_hash'), 'promotion_approvals', ['genome_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promotion_approvals_genome_hash'), table_name='promotion_approvals')
    op.drop_table('promotion_approvals')
    # ### end Alembic commands ###
