"""holdout evaluations and decision evidence

Revision ID: 4daa6685abe3
Revises: 347ef463db86
Create Date: 2026-09-20 22:49:20.681453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4daa6685abe3'
down_revision: Union[str, Sequence[str], None] = '347ef463db86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holdout_evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('genome_hash', sa.String(length=32), nullable=False),
    sa.Column('experiment_id', sa.String(length=100), nullable=True),
    sa.Column('dataset_id', sa.String(length=100), nullable=False),
    sa.Column('dataset_version', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['genome_hash'], ['system_genomes.hash'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('genome_hash', 'dataset_id', 'dataset_version', name='uq_holdout_once')
    )
    op.create_index(op.f('ix_holdout_evaluations_genome_hash'), 'holdout_evaluations', ['genome_hash'], unique=False)
    op.add_column('promotion_decisions', sa.Column('evidence', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promotion_decisions', 'evidence')
    op.drop_index(op.f('ix_holdout_evaluations_genome_hash'), table_name='holdout_evaluations')
    op.drop_table('holdout_evaluations')
    # ### end Alembic commands ###
