"""promotion approval action

Revision ID: c5ae26e681f0
Revises: 4daa6685abe3
Create Date: 2026-09-21 06:33:12.789111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5ae26e681f0'
down_revision: Union[str, Sequence[str], None] = '4daa6685abe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotion_approvals', sa.Column('action', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promotion_approvals', 'action')
    # ### end Alembic commands ###
