"""initial schema

Revision ID: c8fc232e2891
Revises: 
Create Date: 2026-08-31 21:28:48.612143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8fc232e2891'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('applications',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('domain_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('canary_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('baseline_hash', sa.String(length=32), nullable=False),
    sa.Column('candidate_hash', sa.String(length=32), nullable=False),
    sa.Column('traffic_split', sa.Float(), nullable=False),
    sa.Column('rollback_triggered', sa.Boolean(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canary_runs_candidate_hash'), 'canary_runs', ['candidate_hash'], unique=False)
    op.create_table('dataset_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_version', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('dataset_hash', sa.String(length=32), nullable=False),
    sa.Column('difficulty_score', sa.Float(), nullable=False),
    sa.Column('n_challenges', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_hash')
    )
    op.create_index('ix_dataset_id_version', 'dataset_versions', ['dataset_id', 'version'], unique=False)
    op.create_index(op.f('ix_dataset_versions_dataset_id'), 'dataset_versions', ['dataset_id'], unique=False)
    op.create_table('experiments',
    sa.Column('experiment_id', sa.String(length=100), nullable=False),
    sa.Column('application_id', sa.String(length=64), nullable=False),
    sa.Column('domain_name', sa.String(length=100), nullable=False),
    sa.Column('search_strategy', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('experiment_id')
    )
    op.create_index(op.f('ix_experiments_application_id'), 'experiments', ['application_id'], unique=False)
    op.create_table('system_genomes',
    sa.Column('hash', sa.String(length=32), nullable=False),
    sa.Column('system_id', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_hash', sa.String(length=32), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_hash'], ['system_genomes.hash'], ),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_index('ix_genome_system_version', 'system_genomes', ['system_id', 'version'], unique=False)
    op.create_index(op.f('ix_system_genomes_system_id'), 'system_genomes', ['system_id'], unique=False)
    op.create_table('promotion_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('genome_hash', sa.String(length=32), nullable=False),
    sa.Column('experiment_id', sa.String(length=100), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('next_status', sa.String(length=30), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['genome_hash'], ['system_genomes.hash'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotion_decisions_genome_hash'), 'promotion_decisions', ['genome_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promotion_decisions_genome_hash'), table_name='promotion_decisions')
    op.drop_table('promotion_decisions')
    op.drop_index(op.f('ix_system_genomes_system_id'), table_name='system_genomes')
    op.drop_index('ix_genome_system_version', table_name='system_genomes')
    op.drop_table('system_genomes')
    op.drop_index(op.f('ix_experiments_application_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_dataset_versions_dataset_id'), table_name='dataset_versions')
    op.drop_index('ix_dataset_id_version', table_name='dataset_versions')
    op.drop_table('dataset_versions')
    op.drop_index(op.f('ix_canary_runs_candidate_hash'), table_name='canary_runs')
    op.drop_table('canary_runs')
    op.drop_table('audit_log')
    op.drop_table('applications')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
